apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-staging
  namespace: staging
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-staging.yaml
    path: helm
    repoURL: https://github.com/moebius5/udacity-suse-ex5.17
    targetRevision: HEAD
  # Sync policy
  syncPolicy: {}
